language: node_js

node_js:
  - '8.10'

cache:
  directories:
    - api/node_modules
    - frontend/node_modules

env:
  matrix:
    - DIR=./frontend
    - DIR=./api

before_install:
  - cd $DIR

stages:
  - test
  - name: deploy to staging
    # if: branch = master

jobs:
  include:
    - stage: deploy to staging
      env: DIR='./frontend'
      script:
        - pip install --user awscli
        - npm run deploy-stack
        - npm run build
        - npm run deploy
        - npm run invalidate-cache
    - stage: deploy to staging
      env: DIR='./api'
      script: echo "TODO Deploy code to CloudFormation"

